algoritmo "semnome"
// Função :
// Autor :
// Data : 08/01/2020
// Seção de Declarações 
var
   time1, time2, dif: inteiro
inicio
      Escreva("Quantos gols seu time fez: ")
      leia(time1)
      Escreva("Quantos gosl o time adversário fez: ")
      leia(time2)
      
      Escreval("----------------------------")
         dif <- time1 - time2
         
      Escreval(" Diferença: ", (dif))

      Escreval("----------------------------")
fimalgoritmo
