algoritmo "semnome"
// Função :
// Autor :
// Data : 12/01/2020
// Seção de Declarações 
var
   x, y, total: real
   
funcao soma (v1, v2 : real ) : real
 inicio
   retorne v1 + v2
fimfuncao

inicio
   Escreva("Digite o 1° valor: ")
   leia(x)
   Escreva("Digite o 2° valor: ")
   leia(y)
   
   escreval()
   
   total <- soma(x, y)
   Escreva("Soma total: ", total)
   
   escreval()
fimalgoritmo
